- name: reload systemd daemon
  ansible.builtin.systemd_service:
    daemon_reload: true

- name: restart systemd-networkd
  ansible.builtin.systemd_service:
    name: systemd-networkd
    state: restarted
