---
timezone: Europe/Helsinki

package_dependencies:
  - iptables # for docker port forwarding
  - tesseract-data-eng # for kde

basic_packages:
  - ansible
  - emacs
  - iperf3
  - ipmitool
  - iwd
  - man-db
  - man-pages
  - nfs-utils
  - nmap
  - openbsd-netcat
  - openssh
  - pacman-contrib
  - pkgfile
  - rclone
  - reflector
  - ripgrep
  - rsync
  - stow
  - texinfo
  - texlive-basic
  - texlive-bin
  - texlive-latex
  - texlive-latexextra
  - texlive-plaingeneric
  - unzip
  - vim
  - wev
  - zsh
  - zsh-autosuggestions

essential_drivers:
  - bluez
  - bluez-utils
  - inxi
  - pavucontrol
  - pipewire
  - pipewire-alsa
  - pipewire-jack
  - pipewire-pulse
  - rtkit
  - sof-firmware
  - solaar

dev_packages:
  - age
  - ansible
  - ansible-core
  - ansible-lint
  - dbeaver
  - delve
  - direnv
  - docker
  - docker-compose
  - git
  - github-cli
  - go
  - golangci-lint
  - gopls
  - intellij-idea-community-edition
  - jdk21-openjdk
  - jq
  - maven
  - opentofu
  - packer
  - podman
  - sops
  - terraform
  - tflint
  - yq

fonts:
  - freetype2
  - noto-fonts
  - noto-fonts
  - otf-libertinus
  - otf-overpass
  - tex-gyre-fonts
  - ttf-bitstream-vera
  - ttf-caladea
  - ttf-carlito
  - ttf-dejavu
  - ttf-dejavu
  - ttf-dejavu
  - ttf-freefont
  - ttf-inconsolata
  - ttf-jetbrains-mono
  - ttf-jetbrains-mono-nerd
  - ttf-liberation
  - ttf-liberation
  - ttf-liberation
  - ttf-liberation
  - ttf-libertinus
  - ttf-opensans
  - ttf-roboto
  - ttf-ubuntu-font-family
  - ttf-ubuntu-font-family

applications:
  - bitwarden
  - bitwarden-cli
  - btop
  - cups
  - cups-pdf
  - cyme
  - fastfetch
  - firefox
  - grim
  - keepassxc
  - kitty
  - slurp
  - swappy
  - usbutils
  - wl-clipboard

window_managers:
  - greetd
  - greetd-tuigreet
  - hyprland

aur_packages:
  - brother-mfc-l2860dwe
  - google-chrome
  - infisical-bin
  - terraform-ls-bin
  - winbox
  - zen-browser-bin

services_to_enable:
  - bluetooth
  - docker
  - greetd
  - iptables
  - iwd
  - reflector
  - rtkit-daemon
